spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.204:3306/girl
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
